### ISSUE TITLE
Scope for personal access token?

### ISSUE THREAD

**Issue by technicalpickles** [zerowidth/gh-shorthand#3]
`.gh-shorthand.yml` mentions a API token, but it doesn't mention what scope is needed. I'm guessing...  `repo`?

**Comment by zerowidth** [comment]
`read:org, repo, user` is what mine has. I'll make a note to update the docs.

If you're trying this out, use the v2 branch (both here and with the alfredworkflow) -- I can walk you through the setup on slack if you'd like!

**Comment by technicalpickles** [comment]
👍
